### ISSUE TITLE
CMake缺少unofficial-iconv相關依賴

### ISSUE THREAD

**Issue by Chen-Jun-Ren** [ray-cast/RabbitToolbox#61]
**已經將vcpkg.json中所需的依賴安裝完成,但還是會出現以下錯誤**

CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package):
  Could not find a package configuration file provided by "unofficial-iconv"
  with any of the following names:

```
    unofficial-iconvConfig.cmake
    unofficial-iconv-config.cmake
```

  Add the installation prefix of "unofficial-iconv" to CMAKE_PREFIX_PATH or
  set "unofficial-iconv_DIR" to a directory containing one of the above
  files.  If "unofficial-iconv" provides a separate development package or
  SDK, be sure it has been installed.		D:\GitHub\RabbitToolbox\vcpkg/scripts/buildsystems/vcpkg.cmake	857

**Comment by ray-cast** [comment]
vcpkg 的版本是 2020-11-1 这个tag吗

**Comment by Chen-Jun-Ren** [comment]
PS D:\GitHub\RabbitToolbox\vcpkg> ./vcpkg version
Vcpkg package management program version 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

我vcpkg所使用的版本應該是2021-01-13

**Comment by Chen-Jun-Ren** [comment]
我使用TortoiseGit將vcpkg的tag(標籤)修改為2020.11-1後出現了新的問題
CMake會一直卡在[CMake] -- Running vcpkg install沒有其他的動作
